%%
%% Autogenerated by Thrift Compiler (0.7.0-dev)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(scribe_types).

-include("scribe_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('logEntry') ->
  {struct, [{1, string}, {2, string}]}
;

struct_info('i am a dummy struct') -> undefined.

struct_info_ext('logEntry') ->
  {struct, [{1, undefined, string, 'category', undefined}, {2, undefined, string, 'message', undefined}]}
;

struct_info_ext('i am a dummy struct') -> undefined.

